---
name: Publish to npm
on: { release: { types: [created] }, workflow_dispatch: {} }

jobs:
  test:
    runs-on: ubuntu-latest
    permissions: read-all
    steps:
      - { uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 } # v6
      - { uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e, with: { node-version-file: .node-version } } # v6.4.0
      - { uses: oven-sh/setup-bun@0c5077e51419868618aeaa5fe8019c62421857d6 } # v2
      - uses: kjanat/runner@master
      - run: runner install --frozen fmt:check typecheck test

  publish-npm:
    needs: test
    runs-on: ubuntu-latest
    permissions: { contents: read, id-token: write }
    environment: { name: npm, url: "${{ steps.meta.outputs.npm-url }}" }
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with: { persist-credentials: false }
      - uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
        with: { node-version-file: .node-version }
      - uses: oven-sh/setup-bun@0c5077e51419868618aeaa5fe8019c62421857d6 # v2.2.0
      - uses: kjanat/runner@2d2f9eb9825b2d4c9a87cac8a760a69bb80622a1 # v0.12.1
      - id: meta
        run: runner install --frozen meta
      - run: bunx -p=npm@"${NPM_VERSION}" npm publish --provenance --tag latest
